import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'BBQCopilot Terms of Service — Read the terms and conditions governing your use of BBQCopilot.',
  alternates: {
    canonical: 'https://bbqcopilot.com/terms',
  },
};

export default function TermsOfServicePage() {
  return (
    <div className="max-container px-6 py-16 md:px-8 md:py-24 lg:px-12">
      <div className="max-w-3xl mx-auto">
        <h1 className="font-display text-4xl md:text-5xl font-bold text-ash-white mb-4">
          Terms of Service
        </h1>
        <p className="text-char-400 mb-12">Effective Date: February 4, 2026</p>

        <div className="space-y-10 text-char-300 leading-relaxed text-base md:text-lg">
          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using BBQCopilot (the &quot;Service&quot;), you agree to be bound by
              these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, please
              do not use the Service. We reserve the right to update these Terms at any time, and
              your continued use of the Service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              2. Description of Service
            </h2>
            <p>
              BBQCopilot is an AI-powered BBQ recipe and cook planning application that generates
              personalized recipes based on your grilling equipment, skill level, and preferences.
              The Service is available via web and mobile applications.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              3. User Accounts
            </h2>
            <p>
              To use certain features of the Service, you must create an account using an email
              address or Google OAuth. You are responsible for maintaining the confidentiality of
              your account credentials and for all activity that occurs under your account. You agree
              to notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              4. Acceptable Use
            </h2>
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>
                Attempt to interfere with, compromise, or disrupt the Service or its underlying
                infrastructure.
              </li>
              <li>
                Reverse engineer, decompile, or attempt to extract the source code of the Service.
              </li>
              <li>
                Use automated tools, bots, or scripts to access the Service or generate recipes in
                bulk.
              </li>
              <li>
                Resell, redistribute, or commercially exploit AI-generated recipes without
                permission.
              </li>
              <li>
                Create multiple accounts to circumvent usage limits or other restrictions.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              5. AI-Generated Content
            </h2>
            <p>
              Recipes and cook plans generated by BBQCopilot are created using artificial
              intelligence and are provided for informational purposes. While we strive for accuracy,
              AI-generated content may contain errors or inaccuracies. You are responsible for
              reviewing all recipes and using your own judgment when cooking, especially regarding
              food safety, internal temperatures, and allergens.
            </p>
            <p className="mt-3">
              <strong className="text-ash-white">
                BBQCopilot is not a substitute for food safety knowledge.
              </strong>{' '}
              Always follow USDA guidelines for safe minimum internal temperatures and food handling
              practices.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              6. Usage Limits
            </h2>
            <p>
              The Service includes usage limits on recipe generation that vary by plan tier. Free
              accounts are limited to a set number of recipes per month and per day. We reserve the
              right to modify these limits at any time. Exceeding usage limits may result in
              temporary restriction of recipe generation until the next billing or reset period.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              7. Intellectual Property
            </h2>
            <p>
              The Service, including its design, branding, code, and underlying technology, is owned
              by BBQCopilot and protected by intellectual property laws. Recipes you generate are
              yours to use for personal purposes. You retain ownership of any content you submit to
              the Service, such as cook notes, ratings, and photos.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              8. Third-Party Services
            </h2>
            <p>
              The Service integrates with third-party providers including Google (for
              authentication), Anthropic (for AI recipe generation), Supabase (for data storage),
              and PostHog (for analytics). Your use of these integrations is subject to their
              respective terms of service and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              9. Disclaimer of Warranties
            </h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, whether express or implied, including but not limited to
              implied warranties of merchantability, fitness for a particular purpose, and
              non-infringement. We do not warrant that the Service will be uninterrupted,
              error-free, or free of harmful components.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              10. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, BBQCopilot and its operators shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages,
              including but not limited to loss of profits, data, or goodwill, arising out of or
              related to your use of the Service. Our total liability for any claim arising from
              these Terms shall not exceed the amount you paid to us in the 12 months preceding the
              claim.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              11. Account Termination
            </h2>
            <p>
              You may delete your account at any time. We reserve the right to suspend or terminate
              your account if you violate these Terms or engage in conduct that we determine is
              harmful to the Service or other users. Upon termination, your right to use the Service
              ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              12. Changes to Terms
            </h2>
            <p>
              We may revise these Terms at any time by posting the updated version on this page and
              updating the effective date. Material changes will be communicated through the Service.
              Your continued use of the Service after changes are posted constitutes acceptance of
              the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              13. Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              United States, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ash-white mb-4">
              14. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-3">
              <a
                href="mailto:travis.shields@gmail.com"
                className="text-ember-500 hover:text-ember-400 underline transition-colors"
              >
                travis.shields@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
